---
- name : Prepare host for Rancher deployment
  hosts: all
  user: root
  gather_facts: False

  tasks:
  - name: create config file
    file:
      path: /etc/rancher/rke2/
      state: directory

  - name: copy file
    copy:
      dest: /etc/rancher/rke2/config.yaml
      src: config.yaml

  - name: fix network
    copy:
      dest: /etc/NetworkManager/conf.d/rke2-canal.conf
      src: rke2-canal.conf

  - name: Reload service
    ansible.builtin.systemd:
      name: NetworkManager
      state: stopped

  - name: Stop selinux
    command: setenforce 0

  - name: stop firewalld
    ansible.builtin.systemd:
      name: firewalld
      state: stopped

  - name: install chrony
    package:
      name: chrony
      state: present

  - name: Ensure chronyd is active
    service:
      name: chronyd
      state: started

  - name: update the /etc/hosts file
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "172.22.101.101 rancher01.test.local rancher01\n172.22.101.102 rancher02.test.local rancher02\n172.22.101.103 rancher03.test.local rancher03\n172.22.101.102 rancher.test.local rancher"
